services:
    mastermind.puzzle.manager:
      class: MastermindBundle\Manager\PuzzleManager
      arguments: 
        entityManager: "@doctrine.orm.entity_manager"

    mastermind.color.manager:
      class: MastermindBundle\Manager\ColorManager
      arguments: 
        entityManager: "@doctrine.orm.entity_manager"
